energy_dbt:
  target: prod
  outputs:
    prod:
      type: postgres
      host: data_warehouse_postgres
      user: "{{ env_var('DATA_WAREHOUSE_POSTGRES_USER') }}"
      password: "{{ env_var('DATA_WAREHOUSE_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: energy_database
      schema: data
      threads: 10
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1 # default 1 retry on error/timeout when opening connections
